### ISSUE TITLE
Use Generics instead of `any`

### ISSUE THREAD

**Issue by motss** [wilk/microjob#11]
Big thanks to the TypeScript rewrite. Stumbled upon the interface and thinking that this can be improved to leverage the power of the language.

https://github.com/wilk/microjob/blob/ed9bf9ed158514b6c24ca0e3500338b512fb5bab/src/interfaces.ts#L1-L4

I prefer here to accept [Generics][generics-url] instead of using `any`:

```ts
// User can defined its own Generics
// TypeScript also accepts default types, but this requires certain version to support this IIRC.
export interface Config<T = {}, U = {}> {
  ctx?: T;
  data?: U;
}
```

[generics-url]: https://www.typescriptlang.org/docs/handbook/generics.html

**Comment by wilk** [comment]
I like it!
I'll make the change asap: otherwise, please submit a PR and I'll be happy to merge it 💪

**Comment by wilk** [comment]
Fixed in https://github.com/wilk/microjob/pull/13
