### ISSUE TITLE
docs: image broken

### ISSUE THREAD

**Issue by larshp** [wilk/microjob#17]
The image on https://wilk.github.io/microjob/GUIDE.html is broken, looks like the docs are updated manually, so I'm not quite sure how to fix it. Note that the image works for https://github.com/wilk/microjob/blob/master/GUIDE.md

![image](https://user-images.githubusercontent.com/5888506/46254319-c5a29700-c48d-11e8-9389-14497749484c.png)

**Comment by wilk** [comment]
Thanks 💪 
Fix with https://github.com/wilk/microjob/commit/d883208d81915347485ad35b33820333c8c5243b

**Comment by larshp** [comment]
perhaps copy the image under
`"docs": "gitbook build . docs",`
something like
`"docs": "gitbook build . docs && cp something somewhere",`
