### ISSUE TITLE
consider moving compiled docs to gh-pages branch?

### ISSUE THREAD

**Issue by larshp** [wilk/microjob#21]
Hi,
Currently the `master` branch contains both the raw documentation(.md files) and compiled documentation(docs folder).

Consider moving the docs folder to gh-pages branch, this way there will only be one set of original files in the master branch and less updates.

https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Comment by wilk** [comment]
Well, Github allows you to have the docs on master and I don't see a real benefit moving the compiled docs to gh-pages.
However, I think it could be useful to have a "Contribute" section to instruct the contributor on how to update the docs.

**Comment by larshp** [comment]
okay
