### ISSUE TITLE
Add History to docs

### ISSUE THREAD

**Issue by cosminn777** [wilk/microjob#27]
Would like to propose adding a history file to repo so we can spot changes and get help with breaking changes.

**Comment by wilk** [comment]
I like that @cosminn777 !
Do you have any suggestion about a tool to automate the changelog/release process?

**Comment by wilk** [comment]
Gren should fit the current issue: https://github-tools.github.io/github-release-notes/concept.html

**Comment by wilk** [comment]
Added gren support: now there's an updated changelog file and releases have history 🎉
