### ISSUE TITLE
Node 12.5 Deprecation Warning (worker.terminate())

### ISSUE THREAD

**Issue by Haidy777** [wilk/microjob#43]
Hello,

I've just started using this great library. Since 12.5. `worker.terminate()` throws a deprecation Warning, as it returns a Promise now (see https://github.com/nodejs/node/pull/28021).

Correct me if I am wrong, but https://github.com/wilk/microjob/blob/bb031688bac04f957e924fbba90968fa05374866/src/worker-pool.ts#L221 should be the only position where this should be changed?

I'll try to submit a PR to change it.

**Comment by wilk** [comment]
Thank you!
