### ISSUE TITLE
Can't install with node 10.x

### ISSUE THREAD

**Issue by ErunamoJAZZ** [wilk/microjob#45]
Hi, I found your lib today, it look very awesome!, but when I tried to install it, yarn do not allow me because you changed the min versions to 12.6.0:
```
error microjob@0.6.1: The engine "node" is incompatible with this module. Expected version ">=12.6.0". Got "10.16.0"
error Found incompatible module.
```

if it is not because a technical reason, can you delay this constrain until 2019-10-22 when Node12 start its LTS? https://nodejs.org/en/about/releases/

Thanks and have a nice day!

**Comment by wilk** [comment]
Thank you for reporting!
I've updated the Node.js engine mistakenly: I'm reverting it and making sure you're able to use it also with 10.x.

**Comment by wilk** [comment]
Published in version https://github.com/wilk/microjob/releases/tag/v0.6.2.
I'm closing this 🎉
