### ISSUE TITLE
unit tests / CI

### ISSUE THREAD

**Issue by DanielRuf** [wilk/microjob#5]
We should add Travis CI to test every commit and PR of microjob.

**Comment by wilk** [comment]
Hell yeah!
Thank you for opening this issue!
I'll put it on the roadmap 💪

**Comment by motss** [comment]
How about CircleCI?

**Comment by DanielRuf** [comment]
CircleCI is faster, yes. So far Travis CI is more often used and has a good support and also provides OSX images for testing.

Another additional solution is AppVeyor for Windows builds / testing on Windows images.

**Comment by motss** [comment]
I use both TravisCI and CircleCI. Tried AppVeyor but it's way too slow to test on multiple Node.js versions. I gave up using that eventually.

**Comment by DanielRuf** [comment]
> I use both TravisCI and CircleCI. Tried AppVeyor but it's way too slow to test on multiple Node.js versions. I gave up using that eventually.

How do you test on Windows then? CircleCI has no Windows builds and Travis CI too. So AppVeyor is currently the only big option for testing commits on Windows.

**Comment by motss** [comment]
Fun fact is that I code with Windows machine so making assumption that it will work on Windows. For Linux and Mac, I do have Linux and Mac machines plus those CIs to help out.

**Comment by DanielRuf** [comment]
> Fun fact is that I code with Windows machine so making assumption that it will work on Windows. For Linux and Mac, I do have Linux and Mac machines plus those CIs to help out.

But not every project and every contributor ;-)

**Comment by wilk** [comment]
I've integrated Travis for now: https://travis-ci.org/wilk/microjob
If you want to contribute with more tests and feature related to CI/CD, please fill free to open new specific issues and/or PRs 💪
