### ISSUE TITLE
unsupported in {zeit/pkg}

### ISSUE THREAD

**Issue by RezaErfani67** [wilk/microjob#55]
when i convert my app into exe file, return {worker pool has more than 10 worker} in windows server...

**Comment by wilk** [comment]
Can you provide more context please?
What are you using to make an exe file?
What's the error?

**Comment by RezaErfani67** [comment]
i havent tested it but i think resolve [here](https://github.com/zeit/pkg/commit/6bfcb279b59a13e6499221cb73b9deeb916ad1d2)
