### ISSUE TITLE
Hackernoon pictures are missing?

### ISSUE THREAD

**Issue by dalepo** [wilk/microjob#59]
First of all, thanks for this repo.

The [hackernoon](https://hackernoon.com/microjob-a-tiny-multithreading-library-for-node-js-92d0500b07d5) article which contains interesting docs, might have lost all the picture links ? This is the only image I can see.

![image](https://user-images.githubusercontent.com/9423329/76357388-5e317d80-62f6-11ea-96f4-c14b7d1eaceb.png)

I don't know if this is intentional

**Comment by wilk** [comment]
Oops! Nice catch!
I think images disappeared when Hackernoon moved from Medium to their custom platform.
I try to make them back.

Thanks!

**Comment by wilk** [comment]
Ok, I updated the article link with the original one: https://github.com/wilk/microjob/commit/f536a14fbfe389bb01da9963ec9080f8cab31be4
Now you should be able to see the gists.
