### ISSUE TITLE
Unexpected Date format inside worker

### ISSUE THREAD

**Issue by maximelkin** [wilk/microjob#7]
Inside it will be string, not Date

**Comment by wilk** [comment]
Used in data or context?

**Comment by maximelkin** [comment]
In both cases, because JSON.stringify(new Date) gives Date in ISO format as string

**Comment by maximelkin** [comment]
This problem not only for Dates, it's hard to pass custom class objects

**Comment by syberkitten** [comment]
I like this project and would like to recommend for ease of use
not to try to serialize the whole universe into the worker.

try find what is most essentially needed in most cases
and solve this.

If we need to have a specific function inside the worker,
it can be scoped in or required, why the need to serialize Class instance
and / or dates?

**Comment by wilk** [comment]
@maximelkin : if you have some explicit example, please share. it will be useful to use it as a test.

@syberkitten : I don't want to put any limit, for now.
The code passed to `job` is evaluated in a separated context and if you need a function declared in the scope where is invoked job, then you need to pass it as `ctx`.
The same issue applies to any kind of variable: objects, classes, etc.
In any case, if you don't want to serialize anything, just don't use `data` and `ctx` and you're done.

Mind that this lib is based on an experimental api: it may change in future (maybe shared memory with shared context? who knows...).

**Comment by maximelkin** [comment]
Maybe set of default detected classes + special property for classes passed by user?

**Comment by wilk** [comment]
I suggest to add specific unit tests to test out different data structures, both inside context and data.
At least one for each type, both primitives and composites, such as classes and deep nested objects.

Then, let's figure out how to handle the exceptions.

**Comment by vvscode** [comment]
> Data passed between the main page and workers is copied, not shared. Objects are serialized as they're handed to the worker, and subsequently, de-serialized on the other end. The page and worker do not share the same instance, so the end result is that a duplicate is created on each end. Most browsers implement this feature as structured cloning.

https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Transferring_data_to_and_from_workers_further_details

so that's expected behaviour

**Comment by wilk** [comment]
Currently it's not possible to pass class instances via message passing.
For more info take a look to the `passing runtime context` paragraph: https://wilk.github.io/microjob/GUIDE.html#job-context

I'm closing it but I'll reopen if someone finds a way to do it.
